### ISSUE TITLE
convertFromHTML is processing newlines in lists wrong

### ISSUE THREAD

**Issue by remhume** [HubSpot/draft-convert#22]
When having a `<ol>` and in that a `<li>` that has newlines in form of a `<br>` in it, convertFromHTML will make every line in that `<li>` it's own list item, that appears in the surrounding list, which is not the expected result.

Example:
```
<ol>
  <li>first</li>
  <li> second<br>
with<br>
newlines</li>
</ol>
```
will be converted to a list with the structure:
```
1. first
2. second
3. with
4. newlines
```
Every line of the second item is a ContentBlock with type 'ordered-list-item'

**Comment by benbriggs** [comment]
Good catch, I ran into this a few days ago but hadn't started thinking about it yet. The problem stems from `draft-convert` being more strict on keeping a flat block structure. I've found it useful to keep things that way where every visual newline corresponds to a new `ContentBlock`, so `convertToHTML` will split a block at every `<br>` or nested block element.

This method works with most other block types - if the HTML coming in were any other block type, such as `h2` - ```
<h2>
  line one<br>
  line two
</h2>
```

the block type would be expected to be the same, so that the font size & weight are retained. However, for list items this doesn't fly, especially for ordered lists. I'm not sure whether there are any other types of blocks that would cause an issue, if not then I can just add an exception to this strategy for `unordered-list-item` and `ordered-list-item`.

**Comment by benbriggs** [comment]
@remhume I opened a PR for a fix in #28, let me know if you have any questions

**Comment by legrego** [comment]
Similarly, I would expect that an `unstyled` ContentBlock with the content:
 `Hello \n World` (i.e., a soft new-line was entered in between Hello and World) 
would produce this HTML: `<p>Hello <br /> World</p>`.
What we see instead, is: `<p>Hello \n World</p>`, which does not render correctly.

**Comment by benbriggs** [comment]
just opened https://github.com/HubSpot/draft-convert/pull/36 that should be more all-encompassing in fixing this issue. let me know what you think!

**Comment by legrego** [comment]
@benbriggs #36 works perfectly for me! Thank you!

**Comment by benbriggs** [comment]
fixed in `draft-convert@1.4.0` 🎉

**Comment by khrykin** [comment]
Hi, I'm on `1.4.0` and i'm still seeing this not very nice behaviour with lists...
For example, this
```javascript
const html = `
<ul>
  <li>To do 1</li><li>To do 2</li>
</ul>
<ol>
  <li>To do 1</li><li>To do 2</li>
</ol>
`;
```
works as expected:
```
{  
   "entityMap":{  

   },
   "blocks":[  
      {  
         "key":"etpb4",
         "text":" ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      },
      {  
         "key":"pa9r",
         "text":"To do 1",
         "type":"unordered-list-item",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      },
      {  
         "key":"5413d",
         "text":"To do 2",
         "type":"unordered-list-item",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      },
      {  
         "key":"eu8fb",
         "text":"   ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      },
      {  
         "key":"88tf5",
         "text":"To do 1",
         "type":"ordered-list-item",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      },
      {  
         "key":"2ft77",
         "text":"To do 2",
         "type":"ordered-list-item",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      },
      {  
         "key":"2auat",
         "text":" ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[  

         ],
         "entityRanges":[  

         ],
         "data":{  

         }
      }
   ]
}
```
 
but this:
```javascript
const html = `
<ul>
  <li>To do 1</li>
  <li>To do 2</li>
</ul>
<ol>
  <li>To do 1</li>
  <li>To do 2</li>
</ol>
`;
``` 
produces extra unstyled blocks between each `<li>`, resulting in four separate lists:

```
{
   "entityMap":{

   },
   "blocks":[
      {
         "key":"2qq9o",
         "text":" ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"9ogtt",
         "text":"To do 1",
         "type":"unordered-list-item",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"bqhoo",
         "text":" ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"3mert",
         "text":"To do 2",
         "type":"unordered-list-item",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"dd58k",
         "text":"   ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"5c0cc",
         "text":"To do 1",
         "type":"ordered-list-item",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"4qmm5",
         "text":" ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"30o86",
         "text":"To do 2",
         "type":"ordered-list-item",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      },
      {
         "key":"ev7st",
         "text":" ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[

         ],
         "data":{

         }
      }
   ]
}
```

Would be happy to get any help, because eliminating newlines in markup is not really suitable for me...

**Comment by benbriggs** [comment]
@khrykin #42 should fix that, nice catch!

**Comment by benbriggs** [comment]
#42 landed in 1.4.3

**Comment by optimatex** [comment]
Well done. I'm so happy with this module
