### ISSUE TITLE
DraftEntity.create will be deprecated soon.

### ISSUE THREAD

**Issue by oliver4u** [HubSpot/draft-convert#94]
While using `convertFromHTML`, in `htmlToEntity` method, we need to use `Entity.create` to create one draft entity. But console report a warning that "DraftEntity.create will be deprecated soon!" and suggest use `contentState.createEntity` instead.

Question is that there is no contentState yet at the moment...   Any solution or workaround ?

**Comment by benbriggs** [comment]
this is solved in `draft-convert@2.0.0` via #82

**Comment by eessex** [comment]
After bumping to 2.0.0 I am still receiving this error, 
`DraftEntity.create will be deprecated soon!
Please use "contentState.createEntity" instead.`

This is with draft-js 10.3 and React 15.5.4

**Comment by benbriggs** [comment]
@eessex did you switch to the new API using the `createEntity` function passed into `htmlToEntity`/`textToEntity`? a version bump isn't sufficient since the previous method required users to call `Entity.create` within their own code.

**Comment by eessex** [comment]
Thanks @benbriggs - this was the step I was missing, very exciting to see a console empty of warnings!
